# Project: Project1
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = bai1.o
LINKOBJ  = bai1.o
LIBS     = -L"D:/DAI HOC VAN HIEN/CTDLVGT/Dev-Cpp/TDM-GCC-64/lib" -L"D:/DAI HOC VAN HIEN/CTDLVGT/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib" -static-libgcc -mwindows
INCS     = -I"D:/DAI HOC VAN HIEN/CTDLVGT/Dev-Cpp/TDM-GCC-64/include" -I"D:/DAI HOC VAN HIEN/CTDLVGT/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"D:/DAI HOC VAN HIEN/CTDLVGT/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"D:/DAI HOC VAN HIEN/CTDLVGT/Dev-Cpp/TDM-GCC-64/include" -I"D:/DAI HOC VAN HIEN/CTDLVGT/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"D:/DAI HOC VAN HIEN/CTDLVGT/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"D:/DAI HOC VAN HIEN/CTDLVGT/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = Chuong1.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
DEL      = D:\DAI HOC VAN HIEN\CTDLVGT\Dev-Cpp\DevCpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

bai1.o: bai1.cpp
	$(CPP) -c bai1.cpp -o bai1.o $(CXXFLAGS)
